export interface TestCaseResult {
  name: string;
  durationSeconds: number;
  status: "passed" | "failed" | "skipped";
}

export interface ParsedReport {
  cases: TestCaseResult[];
  reportGeneratedAt: Date | null;
}

export interface DetectorConfig {
  /** Minimum number of test cases the report must contain. */
  minExpectedCases?: number;
  /** Minimum average duration per case, in seconds. Below this, the suite likely didn't really run. */
  minAvgDurationSeconds?: number;
  /** Paths that must exist on disk (screenshots, logs) for a run to be considered real. */
  requiredArtifacts?: string[];
  /** The job/pipeline start time. A report older than this was not generated by this run. */
  jobStartedAt?: Date;
}

export interface Signal {
  code: string;
  message: string;
}

export interface DetectionResult {
  ok: boolean;
  signals: Signal[];
  caseCount: number;
  avgDurationSeconds: number;
}
